---
kind: pipeline
type: docker
name: check linux

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - apk add --no-cache git-lfs
      - git clone --recursive $DRONE_REPO_LINK .
      - git checkout $DRONE_COMMIT

  - name: check
    image: rust
    commands:
      - apt-get update -qq
      - apt-get install -qqy llvm-dev libclang-dev clang libspeechd-dev pkg-config libx11-dev libasound2-dev libudev-dev zip
      - cargo check --all

---
kind: pipeline
type: exec
name: check macos

platform:
  os: darwin

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: clone
    commands:
      - git clone --recursive $DRONE_REPO_LINK .
      - git checkout $DRONE_COMMIT

  - name: check
    commands:
      - cargo check --all

---
kind: pipeline
type: docker
name: release linux

trigger:
  branch:
    - release

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - apk add --no-cache git-lfs
      - git clone --recursive $DRONE_REPO_LINK .
      - git checkout $DRONE_COMMIT

  - name: release
    image: rust
    commands:
      - apt-get update -qq
      - apt-get install -qqy llvm-dev libclang-dev clang libspeechd-dev pkg-config libx11-dev libasound2-dev libudev-dev zip
      - cargo install -f cargo-make
      - cargo make -p release release
