---
kind: pipeline
name: linux
type: docker

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    commands:
      - apk add --no-cache git-lfs
      - git clone --recursive $DRONE_REPO_LINK .
      - git checkout $DRONE_COMMIT

  - name: check
    when:
      branch:
        - main
    image: rust
    commands:
      - apt-get update -qq
      - apt-get install -qqy llvm-dev libclang-dev clang libspeechd-dev pkg-config libx11-dev libasound2-dev libudev-dev zip
      - cargo check --all

  - name: release
    when:
      branch:
        - release
    image: rust
    commands:
      - apt-get update -qq
      - apt-get install -qqy llvm-dev libclang-dev clang libspeechd-dev pkg-config libx11-dev libasound2-dev libudev-dev zip
      - cargo install -f cargo-make
      - cargo make -p release release

---
kind: pipeline
name: macos
type: exec

platform:
  os: darwin

clone:
  disable: true

steps:
  - name: clone
    commands:
      - git clone --recursive $DRONE_REPO_LINK .
      - git checkout $DRONE_COMMIT

  - name: default stable
    commands:
      - rustup default stable

  - name: check
    when:
      branch:
        - main
    commands:
      - cargo check --all

  - name: release
    when:
      branch:
        - release
    commands:
      - cargo install -f cargo-make
      - cargo make -p release release
