[package]
name = "rampage"
version = "0.1.0"
authors = ["Nolan Darilek <nolan@thewordnerd.info>"]
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
backtrace = "0.3"
bevy_input_actionmap = { path = "crates/bevy_input_actionmap" }
bevy_tts = { path = "crates/bevy_tts" }

[target.wasm32-unknown-unknown.dependencies]
bevy_webgl2 = { git = "https://github.com/mrk-its/bevy_webgl2", branch = "dev" }
wasm-bindgen = "0.2.69"

[target.wasm32-unknown-unknown.dependencies.bevy]
git = "https://github.com/bevyengine/bevy"
branch = "main"
default-features = false
features = [
    "bevy_winit",
    "render",
]

[profile.dev.package."*"]
opt-level = 3