[env.release]
CARGO_RELEASE_ARGS = "--release"

[tasks.install-trunk]
install_crate = { crate_name = "trunk", binary = "trunk", test_arg = "--help" }

[tasks.install-wasm-bindgen-cli]
install_crate = { crate_name = "wasm-bindgen-cli", version = "0.2.69", binary = "wasm-bindgen", test_arg = "--help" }

[tasks.build]
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
command = "trunk"
args = ["build", "@@split(CARGO_RELEASE_ARGS)"]

[tasks.run]
dependencies = ["install-trunk", "install-wasm-bindgen-cli"]
command = "trunk"
args = ["serve"]