name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v1
      - run: |
          sudo apt-get update
          sudo apt-get install -y libspeechd-dev pkg-config libx11-dev libasound2-dev libudev-dev zip
        if: ${{ runner.os == 'Linux' }}
      - run: |
          choco install -y zip
        if: ${{ runner.os == 'Windows' }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-make
          use-tool-cache: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: make
          args: release -p release
      - uses: actions/upload-artifact@v1
        with:
          name: linux
          path: dist/rampage-linux-x86_64.zip
        if: ${{ runner.os == 'Linux' }}
      - uses: actions/upload-artifact@v1
        with:
          name: macos
          path: dist/rampage.dmg
        if: ${{ runner.os == 'macOS' }}
      - uses: actions/upload-artifact@v1
        with:
          name: windows
          path: dist/rampage-windows-x86_64.zip
        if: ${{ runner.os == 'Windows' }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: linux
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_USER: thewordnerd
          ITCH_GAME: rampage
          CHANNEL: linux-x86_64
          PACKAGE: rampage-linux-x86_64.zip
      - uses: actions/download-artifact@v1
        with:
          name: macos
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_USER: thewordnerd
          ITCH_GAME: rampage
          CHANNEL: macos-x86_64
          PACKAGE: rampage.dmg
      - uses: actions/download-artifact@v1
        with:
          name: windows
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          ITCH_USER: thewordnerd
          ITCH_GAME: rampage
          CHANNEL: windows-x86_64
          PACKAGE: rampage-windows-x86_64.zip
